# Generated by Django 3.0.5 on 2020-05-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='belong_to_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_of_major', to='myauth.Major'),
        ),
    ]
