# Generated by Django 3.0.5 on 2020-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='teamwork.Tag'),
        ),
    ]
