# Generated by Django 3.0.5 on 2020-05-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0003_wanted_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wanted',
            options={},
        ),
    ]
