# Generated by Django 3.0.5 on 2020-04-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='2020', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50)),
                ('short_name', models.CharField(default='', max_length=10)),
                ('total_population', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=100)),
                ('user_type', models.CharField(choices=[('TC', 'Teacher'), ('SD', 'Student')], default='SD', max_length=2)),
                ('head_portrait', models.ImageField(blank=True, null=True, upload_to='portraits', verbose_name='头像')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='电子邮件')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('belong_to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SD_user_grade', to='myauth.Grade', verbose_name='学生用户所处年级')),
                ('belong_to_major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_major', to='myauth.Major', verbose_name='用户所处专业')),
            ],
        ),
    ]
